services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    env_file:
      - ./.env
    build: .
    container_name: api
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
    postgres_data:
      driver: local
