"""empty message

Revision ID: 1ad3039774e3
Revises: 
Create Date: 2024-11-20 18:31:05.894091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '1ad3039774e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spycat',
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('breed', sa.Enum('ABYSSINIAN', 'AEGEAN', 'AMERICAN_BOBTAIL', 'AMERICAN_CURL', 'AMERICAN_SHORTHAIR', 'AMERICAN_WIREHAIR', 'ARABIAN_MAU', 'AUSTRALIAN_MIST', 'BALINESE', 'BAMBINO', 'BENGAL', 'BIRMAN', 'BOMBAY', 'BRITISH_LONGHAIR', 'BRITISH_SHORTHAIR', 'BURMESE', 'BURMILLA', 'CALIFORNIA_SPANGLED', 'CHANTILLY-TIFFANY', 'CHARTREUX', 'CHAUSIE', 'CHEETOH', 'COLORPOINT_SHORTHAIR', 'CORNISH_REX', 'CYMRIC', 'CYPRUS', 'DEVON_REX', 'DONSKOY', 'DRAGON_LI', 'EGYPTIAN_MAU', 'EUROPEAN_BURMESE', 'EXOTIC_SHORTHAIR', 'HAVANA_BROWN', 'HIMALAYAN', 'JAPANESE_BOBTAIL', 'JAVANESE', 'KHAO_MANEE', 'KORAT', 'KURILIAN', 'LAPERM', 'MAINE_COON', 'MALAYAN', 'MANX', 'MUNCHKIN', 'NEBELUNG', 'NORWEGIAN_FOREST_CAT', 'OCICAT', 'ORIENTAL', 'PERSIAN', 'PIXIE-BOB', 'RAGAMUFFIN', 'RAGDOLL', 'RUSSIAN_BLUE', 'SAVANNAH', 'SCOTTISH_FOLD', 'SELKIRK_REX', 'SIAMESE', 'SIBERIAN', 'SINGAPURA', 'SNOWSHOE', 'SOMALI', 'SPHYNX', 'TONKINESE', 'TOYGER', 'TURKISH_ANGORA', 'TURKISH_VAN', 'YORK_CHOCOLATE', name='breeds'), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission',
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spy_cat_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['spy_cat_id'], ['spycat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target')
    op.drop_table('mission')
    op.drop_table('spycat')
    # ### end Alembic commands ###
